### ISSUE TITLE
Energy Charge Broken, Neolith and Probably Every Other Weapon With Charge Broken

### ISSUE THREAD

**Issue by loudpatches** [LOUD-Project/Git-LOUD#128] opened 2024-09-23 05:25 UTC
https://github.com/LOUD-Project/Git-LOUD/commit/69dd3aa7e57098e8c0903cd416c7dec8a744cc53#diff-b8cf95e5068eccf235a419af9c6467fbc753b356e5933ec72c6713e7253b4b13L266

Reverting 

self.EconDrain = CreateEconomyEvent( self.unit, nrgReq, 0, chargetime, ChargeProgress )

to

self.EconDrain = CreateEconomyEvent( self.unit, nrgReq, 0, chargetime - 0.100, ChargeProgress )

seems to fix the observed discrepancy in Neolith DPS calculations where (on 7.10+) it fires every 2 seconds instead of matching the ROF of 1.  Net effect is 2x the firing time and 1/2 damage, as indicated by brewlan damage tester.

Thanks @davidorser

**Comment by Sprouto** [comment] 2024-09-23 05:33
You might want to examine how chargetime is calculated - and what the RateOfFire on the weapon is.   The two are related and the charge isn't the sole control over the firing cycle.

Very likely the RoF is not set high enough, and you're blaming the charge cycle.   A weapon must generate an OnFire event in order to actually start to fire.

**Comment by loudpatches** [comment] 2024-09-23 05:46
It's trivial to test this change and reproduce the discrepancy we observed with Dave.  

- Blueprint was unchanged with no mods (baseline LOUD standard).  Git blame indicated no change on your end.
- The only thing that changed was in your commits, as evidenced by git bisecting to the bad commit.  
- Bisection indicate that this is the commit; reverting changes line by line ended up on this being the breaking change.

7.10
```lua
Phoenix — Yesterday at 10:22 PM
INFO: , 24.199996948242, "srb2402", "Neolith", 825, 750, 784
INFO: , 24.199996948242, "srb2402", "Neolith", 825, 784, 818
INFO: , 26.400001525879, "srb2402", "Neolith", 825, 750, 781
INFO: , 26.400001525879, "srb2402", "Neolith", 825, 781, 812
INFO: , 28.699996948242, "srb2402", "Neolith", 825, 747, 776
INFO: , 28.699996948242, "srb2402", "Neolith", 825, 776, 805
INFO: , 30.900001525879, "srb2402", "Neolith", 825, 748, 774
INFO: , 30.900001525879, "srb2402", "Neolith", 825, 774, 801
```
7.09
```lua
INFO: , 1.0999984741211, "srb2402", "Neolith", 825, 1500, 2250
INFO: , 1.0999984741211, "srb2402", "Neolith", 825, 2250, 3000
INFO: , 2.1999969482422, "srb2402", "Neolith", 825, 1500, 1875
INFO: , 2.1999969482422, "srb2402", "Neolith", 825, 1875, 2250
INFO: , 3.3000030517578, "srb2402", "Neolith", 825, 1500, 1750
INFO: , 3.4000015258789, "srb2402", "Neolith", 825, 1699, 1941
INFO: , 4.4000015258789, "srb2402", "Neolith", 825, 1500, 1687
INFO: , 4.4000015258789, "srb2402", "Neolith", 825, 1687, 1875
INFO: , 5.5999984741211, "srb2402", "Neolith", 825, 1473, 1621
INFO: , 5.5999984741211, "srb2402", "Neolith", 825, 1621, 1768
INFO: , 6.5999984741211, "srb2402", "Neolith", 825, 1500, 1625
INFO: , 6.6999969482422, "srb2402", "Neolith", 825, 1601, 1724
INFO: , 7.6999969482422, "srb2402", "Neolith", 825, 1500, 1607
INFO: , 7.6999969482422, "srb2402", "Neolith", 825, 1607, 1714
INFO: , 8.8000030517578, "srb2402", "Neolith", 825, 1500, 1594
INFO: , 8.8000030517578, "srb2402", "Neolith", 825, 1594, 1687
INFO: , 9.9000015258789, "srb2402", "Neolith", 825, 1500, 1583
INFO: , 9.9000015258789, "srb2402", "Neolith", 825, 1583, 1667
```

The alternative is that you intended this change to induce the neolith to deal 1/2 DPS and have PHXLib report incorrect DPS in the stats. 

It sound counterintuitive based on your own comments in the blueprint https://github.com/LOUD-Project/Git-LOUD/blob/master/gamedata/BrewLAN_LOUD/mods/BrewLAN_LOUD/units/SRB2402/SRB2402_unit.bp#L309

```lua
RateOfFire = 1,     -- 1650 DPS - controlled by energy -- 2 x 750 every second
```

 I did not read that in the change log if you intended to change the DPS from 1650 to ~800.

**Comment by davidorser** [comment] 2024-09-23 12:56
Sorry short comment, headed to work. 

It is possible that reducing the energy recharge time by 0.1 causes the weapon to barely miss its next On fire event. This then might result in a full additional RateOfCycle before firing (+1sec). 

For context, sprout we zoomed in and watched a neolith charge to full in 1sec the sit quietly for another 1sec before firing a second volley.

**Comment by Sprouto** [comment] 2024-09-23 14:03
Hence my point about using the Debug Tools to actually see what is happening.   Never rely upon visual observation to ascertain the reality of the mechanics.

David has pointed out the correct assessment.   The weapon is missing it's next OnFire call, which can be tackled from a number of directions, either thru use of other states, such as the rack reload, which will delay the return to the Idle State (where the OnFire event is generated).

The internal comments are, in some cases, quite old and no inference about intent should ever been drawn from them, as they can be entirely out of context, especially when linked to changes elsewhere.   There was no intent to alter DPS.

**Comment by Sprouto** [comment] 2024-09-23 14:51
At this point, it's clear that the answer lies in the unit itself - so I'll close this issue.

**Closed by Sprouto** 2024-09-23 14:51 UTC

**Comment by The-Balthazar** [comment] 2024-09-23 16:53
I don't like the concept that the same blueprint stats have vastly different outcomes depending on where you use the unit. That seems to me not a unit issue.

**Comment by Sprouto** [comment] 2024-10-01 20:02
Getting back to the specifics here, the current codebase is correct, with the Economy Event now taking precisely 1 second (as indicated in the blueprint) and not .9 seconds (which it was doing with the requested reversion).  If you revert the change, not only is the time period shorter, but the UI indicated drain will be higher, and not match the blueprint.

So - what is the delay ?

The blueprint RateOfFire = 1 will generate an OnFire() event every second, and, as surmised, because the charge cycle is one full second, the weapon will miss every other OnFire().   

This can be addressed in a couple of different ways - since we are now decoupled from RateOfFire, setting this value to 10, will generate a potential OnFire() event every tick, so the weapon should fire on every 11th tick.   Still not ideal - as the EconomyEvent only ends on the very tick we want to fire on.   This is not exactly what we get - it fires on every 12th tick - and I'm not exactly sure as to why.   Time to turn on the AI Debug tools to see the tick accurate timing of the vents in play.

After the weapon fires, it proceeds to the RackSalvoReload State, and in here, the AI Debug tools reveal an extra delay between the start of this state, and moving back to the RackSalvoCharge State.  This delay is actually being caused by the rack recoil process.   This delay should be inconsequential, as the EconomyEvent, which started as the weapon fired, should still be underway.   We see something absolutely new here - the RackRecoilReturnSpeed, which is intended to directly control the speed of the recoil animation, if there is a RackRecoilDistance specified in the weapon blueprint (and there is in this case).

The RackRecoilReturnSpeed is actually a weapon blueprint value that we never see specified anywhere - the reason being is that it's defaulted, if not provided, based upon the distance, and the RateOfFire.   A solution for sure, to make sure the recoil is complete prior to the next OnFire() event, but not necessarily correct in an instance such as this.   However, not related to this timing issue.    As we move the RateOfFire value up, to get the desired tick for firing, this recoil speed is accelerated, to the point where the recoil is nearly instant (except for a 1 tick delay).   Another case of unintended results and another reason why I began the process of trying to dis-entangle all of these weapon features in the first place.

**Comment by The-Balthazar** [comment] 2024-10-01 21:17
I am not particularly interested in if it seems more correct in the internal logic to do things differently if it results in the same blueprint values having a different result in different versions of the game. It's widening the gulf between LOUD and other versions of the game for what appears to be a nitpick, and is essentially cutting off any external content from functioning correct, as originally designed, within LOUD. Speaking as an author of both mods and evaluation software such as the wiki generator, that sort of change makes what I'm trying to do considerably harder.

**Comment by Sprouto** [comment] 2024-10-01 21:31
Just trying to make sense of it - it's not about philosophy.   

The weapon processing started out as a very convoluted process with dozens of shortcuts and hidden abilities - the visible functioning, with respect to things like energy consumption, and rate of fire, and other features, and how that translates to someone creating units, or modifying blueprints, is clearly a guessing game.   It seems I'm often damned no matter which way it goes.
