### ISSUE TITLE
Can't start a game when the mod "LOUD Integrated Storage" is enabled

### ISSUE THREAD

**Issue by GeneralDuke9** [LOUD-Project/Git-LOUD#94] opened 2024-06-30 15:34 UTC
I just updated my game data with the LOUD game launcher. Unfortunately I'm no longer able to launch a game (neither a skirmish for myself nor on a shared server), I'm seeing the following error in the logs:

```
info: *DEBUG simInit begins
info: *DEBUG GlobalInit begins
info: *AI DEBUG     Implementing Import
info: *AI DEBUG     Implementing Utils
info: *AI DEBUG     Implementing REPR functions
info: *AI DEBUG     Loading Class FUnctions
info: *AI DEBUG     Defining TRASHBAG Class
info: *AI DEBUG     Localization begins
info: Hooked /loc/us/strings_db.lua with /mods/brewlan_loud/hook/loc/us/strings_db.lua
info: Hooked /loc/us/strings_db.lua with /mods/totalmayhem/hook/loc/us/strings_db.lua
info: Hooked /loc/us/strings_db.lua with /mods/loud unit additions/hook/loc/us/strings_db.lua
info: *DEBUG GlobalInit Complete
info: *AI DEBUG     Setup Platoon Template Structure
info: *AI DEBUG     Setup Builder Template Structure
info: *AI DEBUG     Setup Builder Group Structure
info: *AI DEBUG     Setup BaseBuilder Template Structure
info: *AI DEBUG     Setup BUFF system structure
info: *AI DEBUG     Loading Adjacency Buff functions
info: *AI DEBUG     Loading Buff Blueprint Definitions
info: *AI DEBUG     Loading Adjacency Buff Definitions
warning: ...nce\loud\gamedata\lua.scd\lua\sim\adjacencybuffs.lua(139): attempt to perform arithmetic on field `STRUCTURE' (a nil value)
warning: stack traceback:
warning:         ...nce\loud\gamedata\lua.scd\lua\sim\adjacencybuffs.lua(139): in main chunk
warning:         [C]: in function `doscript'
warning:         [C]: in function `pcall'
warning:         ...alliance\loud\gamedata\lua.scd\lua\system\import.lua(61): in function `import'
warning:         ...orged alliance\loud\gamedata\lua.scd\lua\siminit.lua(71): in main chunk
warning: Error in file /lua/simInit.lua : ...orged alliance\loud\gamedata\lua.scd\lua\siminit.lua(71): Error importing '/lua/sim/adjacencybuffs.lua'
         stack traceback:
         	[C]: in function `error'
         	...alliance\loud\gamedata\lua.scd\lua\system\import.lua(66): in function `import'
         	...orged alliance\loud\gamedata\lua.scd\lua\siminit.lua(71): in main chunk
debug: MEM: 0 bytes OGRID
info: Sim::Create() crashed: attempt to call a nil value
      stack traceback:
info: Minimized true
```

When disabling the 'official rebalance' mod "LOUD Integrated Storage" it worked without problems, so there's probably an issue with the fact that there are no longer mass extractor adjacency bonuses.

**Comment by Sprouto** [comment] 2024-06-30 15:40
I would require your complete LOG file to diagnose this directly - but we have information telling us that this is being caused by the Tanksys Reelism mod.    Please start your diagnosis by disabling ALL mods - and seeing if the error persists - and then by reintroducing one mod at a time.

**Comment by GeneralDuke9** [comment] 2024-06-30 15:59
Hiya,

Thanks for the quick reply!
I've established that it fails when using the LOUD Integrated Storage mod in combination with the BrewLAN for LOUD mod. See the full log attached.

Cheers.
[Loud_Integrated_Storage_and_BrewLAN_for_LOUD.log](https://github.com/user-attachments/files/16045266/Loud_Integrated_Storage_and_BrewLAN_for_LOUD.log)

**Comment by Sprouto** [comment] 2024-06-30 18:54
Ok - this may make some sense - or it may not.   Integrated Storage is expecting to see certain units present - namely the upgradeable storage buildings from Black Ops Unleashed.    When those are NOT present - IS is basically creating an incomplete blueprint for a unit that will never be in the game - and that blueprint is missing all of it's categories.    Later on, in the BrewLAN loading process, it will attempt to process ALL the blueprints - evaluating each units category table - which, in this case, doesn't exist - thus causing an error.

To solve it immediately - turn on Black Ops Unleashed - and the necessary units will be filled in properly - otherwise - you'll have to wait until I patch the mod_blueprints function in BrewLAN, which at this point, may be a week or more before I patch again.

**Comment by Sprouto** [comment] 2024-06-30 18:54
I'm going to close this issue now that we understand it's source.

**Closed by Sprouto** 2024-06-30 18:54 UTC

**Comment by GeneralDuke9** [comment] 2024-06-30 19:49
Thanks for the workaround, I’ll give it a go.

Cheers!
